### ISSUE TITLE
FVA is slow on windows and sometimes linux

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#169]
Maybe this is caused by bad multithreading? Set number of processes to 1?
https://cobrapy.readthedocs.io/en/latest/autoapi/cobra/index.html?highlight=processes#cobra.Configuration.processes

**Comment by axelvonkamp** [comment]
Current workaround for Windows: Set number of processes in cobra.Configuration() to 1, e.g. via the "Configure COBRApy" dialog. I haven't had problems with Linux so far, does someone have a reproducible setup that is slow on Linux?

**Comment by sthiele** [comment]
Maybe @Paulocracy ?
