### ISSUE TITLE
MCS consider reaction box values

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#199]
MCS dialog provides checkbox for using reaction box values. CNApy calls MATLAB function "cnapy_compute_mcs" with the variable "reac_box_values=1" to read out reaction boxes from GUI. As there is no MATLAB-GUI, this call fails and throws an error.

Solution proposal: 
cnapy/gui_elements/mcs_dialog.py should use the parameter reac_box_values to pass the values in the reaction boxes directly instead of serving as a flag. Reaction boxes are accessible from python.

These are the positions that are concerned:
https://github.com/cnapy-org/CNApy/blob/aae5f61a05de299ef382d512fd9b4ef8c1c245f3/cnapy/gui_elements/mcs_dialog.py#L345-L348

https://github.com/cnapy-org/CNApy/blob/aae5f61a05de299ef382d512fd9b4ef8c1c245f3/cnapy/gui_elements/mcs_dialog.py#L388

https://github.com/cnapy-org/CNApy/blob/aae5f61a05de299ef382d512fd9b4ef8c1c245f3/cnapy/gui_elements/mcs_dialog.py#L409

**Comment by axelvonkamp** [comment]
The scenario values are now integrated into the model bounds which makes the reac_box_vals parameter obsolete (branch mcs_wip).
