### ISSUE TITLE
Flux values outside the min-max range of a reaction can be entered on the map

### ISSUE THREAD

**Issue by axelvonkamp** [cnapy-org/CNApy#200]
For instance a negative flux value can be entered for an irreversible reaction making FBA infeasible. This should be prevented.

**Comment by sthiele** [comment]
The semantics should be that the scenario value overwrites the bounds in the model.

**Comment by axelvonkamp** [comment]
OK, should the scenario values then temporarily overwrite the model bounds before e.g. FBA? Right now, when I for example set R1 = -1 in SmallExample FBA becomes infeasible because R1 is irreversible.

**Comment by sthiele** [comment]
> OK, should the scenario values then temporarily overwrite the model bounds before e.g. FBA?
Yes. I think `load_scenario_into_model` should do that?

**Comment by sthiele** [comment]
> Right now, when I for example set R1 = -1 in SmallExample FBA becomes infeasible 

I think it is because the direction(-1) does not match with the directions of R5,R6 and R7.

**Comment by sthiele** [comment]
Maybe we should mark scenario values which contradict the model bounds?

**Comment by axelvonkamp** [comment]
Yes, I think that is a good idea.

**Comment by sthiele** [comment]
If a scenario value contradicts the model bound then the reaction box is rendered with a frame in yellow.
