### ISSUE TITLE
Compute EFMs via EFMtool crashes CNApy (on Windows)

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#213]
Error produced with SmallExample.
efmtool4cobra isn't able to get reversibilities.

`Traceback (most recent call last):`
`File "C:\Users\phili\cnapy\cnapy\cnapy\gui_elements\efmtool_dialog.py", line 45, in compute    `                           `self.constraints.checkState() == Qt.Checked) `
`File "C:\Users\phili\cnapy\cnapy\cnapy\core.py", line 16, in efm_computation `
`reversible, irrev_backwards_idx = efmtool4cobra.get_reversibility(`
`AttributeError: module 'efmtool_link.efmtool4cobra' has no attribute 'get_reversibility' `

**Comment by axelvonkamp** [comment]
I do not get this error. The error indicates that for some reason the efmtool_link package is not up to date.

**Comment by sthiele** [comment]
@VonAlphaBisZulu Did it not install correctly?

**Comment by VonAlphaBisZulu** [comment]
I used the Github version but forgot emftool_link is a separate package. Works fine after updating emftool_link. Sorry for the Issue.

**Comment by sthiele** [comment]
No thanks for opening the issues that makes it much easier for us.
