### ISSUE TITLE
Loading EFMs and then clearing/closing EFMs crashes CNApy

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#214]
`Traceback (most recent call last):`
`File "C:\Users\phili\cnapy\cnapy\cnapy\gui_elements\modenavigator.py", line 65, in clear`
`self.appdata.project.modes.clear()`
`File "C:\Users\phili\cnapy\cnapy\cnapy\flux_vector_container.py", line 39, in clear`
`self.reac_id.clear()`
`AttributeError: 'numpy.ndarray' object has no attribute 'clear' `

**Comment by axelvonkamp** [comment]
Is the call self.appdata.project.modes.clear() really necessary?

**Comment by sthiele** [comment]
That could work, but keep in mind that the memory will not be freed as long as still hold a reference to that data. I think there can be a lot of modes :rocket:.
What would be the process to access the modes after I trash/close the mode navigator?

**Comment by sthiele** [comment]
We could separate EFM and MCS Navigator. At the time I implemented it both were so similar that it made sense to combine these.
