### ISSUE TITLE
Editing a gene reaction rule creates many new orphaned genes

### ISSUE THREAD

**Issue by Paulocracy** [cnapy-org/CNApy#329]
Right now, when I edit a gene reaction rule, CNApy doesn't await me leaving the edit line's focus, so that in the course of my writing many new and immediately orphaned genes are generated. This should be changed so that new genes are only generated when I leave the line's focus, or, alternatively, by finding a way that allows one to delete orphaned genes.

**Comment by axelvonkamp** [comment]
Editing a GPR rule does not yet mark the model as changed.
It should be possible to add a "Delete gene" button using the delete_genes function from cobra.manipulation.delete.
