### ISSUE TITLE
Auto-FBA doesn't update when flux boundaries are changed

### ISSUE THREAD

**Issue by VonAlphaBisZulu** [cnapy-org/CNApy#339]
- When entering new flux bounds, auto-FBA doesn't update
- When changing another flux in the scenario, new flux bounds are not considered

**Comment by axelvonkamp** [comment]
The first point is correct, auto-FBA currently reacts to scenario changes only, will make it to react to reaction changes as well.
I not quite sure that I understand the second point, can you give me an example?
