### ISSUE TITLE
problem map darstellung unter linux

### ISSUE THREAD

**Issue by SteffKlamt** [cnapy-org/CNApy#377]
this happens only under linux, not under windows

![tt](https://user-images.githubusercontent.com/34655024/171871026-bf6216a8-4fe3-4fc7-94e9-24cb07dabb06.png)

**Comment by VonAlphaBisZulu** [comment]
This seems to be an issue with qtpy under Linux. In particular with svg rendering, when background is created as `QGraphicsSvgItem` object. 

Created a [new release for the CNApy projects (v0.0.6)](https://github.com/cnapy-org/CNApy-projects/releases/tag/0.0.6), where all texts were converted to paths. This should fix the rendering related issues.
