### ISSUE TITLE
Escher map not working

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#411]
I made some videos of the issue. Maybe this helps finding out whats going on.

https://user-images.githubusercontent.com/1641315/192118511-3f1a50d3-6f5e-47d6-aaa2-1ce1a08dcfa1.mp4

https://user-images.githubusercontent.com/1641315/192118513-6fcc8ea5-577a-41db-aa1a-7c036fd86b7d.mp4

**Comment by axelvonkamp** [comment]
Is there any output on the console from which cnapy was started? When loading e_coli_core_escher.cna with the current master the messages:

js: Loading map
finish_setup

should appear.

**Comment by sthiele** [comment]
No there is no such output.

**Comment by axelvonkamp** [comment]
So I guess pyqt and pyqtwebengine should be at least version 5.12?

**Comment by sthiele** [comment]
We should definitely use pyqtwebengine from conda-forge,
Maybe it is worth looking into what other dependencies could be updated.
Can we just loosen the minimal version dependencies, or should we fix a version?
If everybody has the same versions it would make debugging easier that would include fixing the version in the receipies at least for the same platforms.

**Comment by sthiele** [comment]
BTW: The escher maps look nice. :1st_place_medal: 
I finally get some js errors :stuck_out_tongue_winking_eye:  :

```
js: Uncaught ReferenceError: builder is not defined
js: Uncaught TypeError: Cannot read property 'style' of undefined
```

**Comment by axelvonkamp** [comment]
> BTW: The escher maps look nice. 1st_place_medal I finally get some js errors stuck_out_tongue_winking_eye :
> 
> ```
> js: Uncaught ReferenceError: builder is not defined
> js: Uncaught TypeError: Cannot read property 'style' of undefined
> ```

But it is working nonetheless?

**Comment by sthiele** [comment]
> But it is working nonetheless?
Yes, the map is displayed and functional i can navigate and the flux values are color coded.

**Comment by sthiele** [comment]
Actually the error messages above might be a product of my debugging attempts. In the clean branch i still get js errors but these:
```
js: Error: <rect> attribute height: A negative value is not valid. ("-100")
js: Error: <rect> attribute height: A negative value is not valid. ("-100")
js: Error: <rect> attribute width: A negative value is not valid. ("-100")
js: Error: <rect> attribute width: A negative value is not valid. ("-100")
js: Bad scale value
js: Loading map
js: Bad scale value
```

**Comment by sthiele** [comment]
This was `ecoli_core_escher.cna`.

**Comment by axelvonkamp** [comment]
And this is with Qt 5.12 or 5.15 (I currently have 5.12)?

**Comment by sthiele** [comment]
5.15.7

**Comment by axelvonkamp** [comment]
OK, I will switch to this version and see if I get this too.

**Comment by sthiele** [comment]
But it seams i still have two qt versions 
```
❯ conda env export | grep qt
  - pyqt=5.15.7=py38h7492b6b_1
  - pyqt5-sip=12.11.0=py38hfa26641_1
  - pyqtwebengine=5.15.7=py38h7492b6b_1
  - qt-main=5.15.6=hc525480_0
  - qt-webengine=5.15.4=hcbadb6c_3
  - qtconsole=5.3.2=pyhd8ed1ab_0
  - qtconsole-base=5.3.2=pyha770c72_0
  - qtpy=2.2.1=pyhd8ed1ab_0
```

Also I remove pyside from my `environment.ym`l as it seems not to be used because we go over qtpy

**Comment by axelvonkamp** [comment]
I also get these weird error messages with 5.15.7. As far as I can see everything works as expected though. I will investigate further...

**Comment by axelvonkamp** [comment]
My guess is that the error messages are from D3.js and are from Escher's initial setup when it generates a default map. This happens all before the map from the CNApy project is loaded. I don't know why these messages appear with Qt 5.15 but and not with 5.12 but the operation of Escher does not appear to be affected.
