### ISSUE TITLE
Choose between all and main projects when downloading

### ISSUE THREAD

**Issue by axelvonkamp** [cnapy-org/CNApy#425]
When downloading the cnapy-projects via CNApy's GUI offer a choice between downloading all or the main models only.

**Comment by Paulocracy** [comment]
That's a great idea. What would be your definition of "main" models?

**Comment by axelvonkamp** [comment]
Currently [these](https://github.com/cnapy-org/CNApy-projects/commit/e03055b38cdf33a37634969e6fd6b88d826b86fd). Perhaps also some yeast model when one is available.

**Comment by axelvonkamp** [comment]
implemented with #429
