### ISSUE TITLE
minimal cut sets error

### ISSUE THREAD

**Issue by parsanayyara** [cnapy-org/CNApy#462]
Hi, I was trying to compute minimal cut sets in CNApy and it keeps returning this error. Can anyone explain why this happens and how I can fix it? I am new to CNApy so any help would be much appreciated!

<img width="477" alt="image" src="https://user-images.githubusercontent.com/77234398/220971903-6d4257bf-ebdf-4f52-8b35-fb72222a4b1b.png">

**Comment by axelvonkamp** [comment]
Can you mail me (vonkamp@mpi-magdeburg.mpg.de) the .cna project and describe which constraints you have used for the cut sets problem?
As a workaround, you can also use strain design to calculate cut sets, it is a different implementation and hopefully it should work there.

**Comment by axelvonkamp** [comment]
Please update to the latest CNApy version, this should fix the problem.
