### ISSUE TITLE
Make scenario feasible error 

### ISSUE THREAD

**Issue by dtusso2020** [cnapy-org/CNApy#467]
Hello

When I use the option make scenario feasible I get this error:
`Traceback (most recent call last): File "C:\Users\diana\anaconda3\envs\cnapy-1.1.6\lib\site-packages\cnapy\gui_elements\flux_feasibility_dialog.py", line 286, in compute if self.modified_scenario is self.appdata.scenario_past[-1]: IndexError: list index out of range `
 How could I fix it?.

Thank you.

**Comment by axelvonkamp** [comment]
Hi,

this has been fixed, but is not yet released. As a workaround you can just enter some scenario value for an arbitrary reaction and then remove it again (not undo) so that the scenario history is not emtpy.

-Axel
