### ISSUE TITLE
Allow to set feasibility tolerance in optlang

### ISSUE THREAD

**Issue by sthiele** [cnapy-org/CNApy#50]
Needs investigation

**Comment by sthiele** [comment]
Related #33

**Comment by axelvonkamp** [comment]
When setting the model tolerance (e.g. via the "Configure COBRApy" dialog) this value is propagated to the feasibility tolerance of the underlying optlang model.

**Comment by sthiele** [comment]
@axelvonkamp Can this be closed?

**Comment by axelvonkamp** [comment]
Yes.
